@startuml

package "Nuestra infraestructura" {

    node "Servidor de\nRecomendación" {
    component "Servicio de\nRecomendación" as service
    }

    node "Servidor de\nbase de datos" {
    component "DB MySQL" as db
    }

    node "Servidor de\naplicación" {
    component "Aplicacion Web\nproveedora de\ncolaboradores" as app
    }

    interface "http (REST)" as app_interface
    interface "tcp/ip" as db_interface

    app --( app_interface
    service -- app_interface
}

interface "https (REST)" as service_interface

note right of service_interface
    Interfaz de
    comunicación con el
    servicio de recomendación
endnote

db -- db_interface
db_interface )- service
service --- service_interface

@enduml