### Bad request
POST http://localhost:8080/colaboradores
content-type: application/json

[
    {
    "nro_documento": "123456789"
    }
]


### Good request
POST http://localhost:8080/colaboradores
content-type: application/json

[
    {
      "id": 1234234,
    "nro_documento": "123456789",
    "tipo_documento": "DNI",
    "puntos": 40.0,
    "donaciones": 1
    }
]

### Good request
POST http://localhost:8080/colaboradores
content-type: application/json

[
  {
    "id": 1,
    "nro_documento": "12345678",
    "tipo_documento": "DNI",
    "puntos": 45000.0,
    "donaciones": 510
  },
  {
    "id": 250,
    "nro_documento": "12345679",
    "tipo_documento": "DNI",
    "puntos": 40.0,
    "donaciones": 510
  }
]